name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-token: ${{ secrets.HUB_TOKEN }}
          modrinth-id: rQf7vUve
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: ./@(common|forge|fabric)/build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: ./@(common|forge|fabric)/build/libs/*-@(dev|sources|javadoc).jar
