name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Box Common JARs
        uses: actions/upload-artifact@v3
        with:
          name: common
          path: common/build/libs
      - name: Box Fabric JARs
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs
      - name: Box Forge JARs
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: forge/build/libs

  deploy-github:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Unbox common JARs
        uses: actions/download-artifact@v3
        with:
          name: common
          path: build/common
      - name: Unbox Fabric JARs
        uses: actions/download-artifact@v3
        with:
          name: fabric
          path: build/fabric
      - name: Unbox Forge JARs
        uses: actions/download-artifact@v3
        with:
          name: forge
          path: build/forge
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-token: ${{ secrets.HUB_TOKEN }}
          files-primary: "build/(forge|fabric)/!(*-(sources|dev|shadow)).jar"

  deploy-fabric:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Unbox Fabric JARs
        uses: actions/download-artifact@v3
        with:
          name: fabric
          path: build/fabric
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: fabric
          modrinth-id: rQf7vUve
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 711489
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: "build/fabric/!(*-(sources|dev|shadow)).jar"

  deploy-forge:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Unbox Forge JARs
        uses: actions/download-artifact@v3
        with:
          name: forge
          path: build/forge
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: forge
          modrinth-id: rQf7vUve
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 711489
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: "build/forge/!(*-(sources|dev|shadow)).jar"
